user_input_analyzer_task:
  description: >
    Analyze the {user_input} and find out the main keywords in needed language and date range to search the news.
    find out which country to search the news.
    the current date is {date}.
  expected_output: >
    The main keywords, date range, country for perfect news search
  agent: user_input_analyzer

news_researcher_task:
  description: >
    the current date is {date}.
    from last task, you've got the main keywords, date range, country for perfect news search.
    Make sure you find any interesting and relevant information given the main keywords, date range, country.
    Get the list of 10 websites with the most relevant information about the main keywords
    And rank the list by relevance to the main keywords.
  expected_output: >
    The list of top 5 websites with the most relevant information about the main keywords
  agent: news_researcher

news_scraper_task:
  description: >
    Scrape the websites on the list from last task 
  expected_output: >
    Fully scraped websites with all the important information from the website.
  agent: news_scraper

news_summarizer_task:
  description: >
    the current date is {date}.
    Summarize the information from the fully scraped websites from last task into a fully fledge news article in markdown format.
    if the language is not Korean, translate the summary into Korean.
    Make sure to include all the important information from the websites.
    Make sure to include the date of the news article.
    Make sure to include the source of the news articles.
    Make sure to include url and reference of each website.

  expected_output: >
    A fully fledge news article with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: news_summarizer

file_writer_task:
  description: >
    make the news article you got from last task into a file
  expected_output: >
    A fully fledge news article with all information from previous task into a file named news/{date}_news_article.md
  agent: file_writer