research_analyzer_task:
  description: >
    Analyze {user_input} and classify the user's input into one of the following categories:
    1. "paper_search"
    2. "news_search"
    3. "keyword_search"

    paper_search is for searching academic papers. suitable for user input that needs to search academic papers.
    news_search is for searching news articles. suitable for user input that needs to search news articles.
    keyword_search is for searching only keywords. suitable for user input that needs to search keywords.

  expected_output: >
    A string containing the category of the user's input.
  agent: research_analyzer